"""Utilities package"""
from .logger import setup_logger, get_logger
from .text_processing import (
    split_sentences,
    count_words,
    count_sentences,
    calculate_average_sentence_length,
    calculate_sentence_length_variance,
    calculate_burstiness_score,
    extract_numbers,
    find_banned_words,
    count_word_frequency,
    truncate_text,
    clean_whitespace,
    split_into_chunks,
    merge_sentences,
    split_long_sentence,
    normalize_spaces_around_punctuation,
    extract_paragraphs,
)

__all__ = [
    "setup_logger",
    "get_logger",
    "split_sentences",
    "count_words",
    "count_sentences",
    "calculate_average_sentence_length",
    "calculate_sentence_length_variance",
    "calculate_burstiness_score",
    "extract_numbers",
    "find_banned_words",
    "count_word_frequency",
    "truncate_text",
    "clean_whitespace",
    "split_into_chunks",
    "merge_sentences",
    "split_long_sentence",
    "normalize_spaces_around_punctuation",
    "extract_paragraphs",
]
